
"""Ved_1503_Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hAoCqaqIZTFYYTjHuL7P7BIa29Cx4BPq
"""

# Continuing from 14 March 
# Check Plagarism between two files 
# Output : Return the Plagerism between 2 files
# Plagerism : Total numbers of common words between two files/max(length of file1,length of file 2)*100


file1 = open("file1.txt","w")
file1.writelines("Hello brother! How you doing? I hope everything is fine")
file1.close()
file2 = open("file2.txt","w")
file2.writelines("Hey! I heared you doing very well.Btw hello")
# file2.writelines("Hello brother! How you doing? I hope everything is")
file2.close()

def check_plag(file1,file2):
  list1=file1.read().split()
  list2=file2.read().split()
  print(list1)
  print(list2)
  s=set(list2).intersection(set(list2))
  counter = 0
  for i in s:
    counter = counter + min(list1.count(i),list2.count(i))
  p=counter/max(len(list2),len(list2))*100
  return p

fil1= open("file1.txt","r")
fil2= open("file2.txt","r")
# print(fil1.readlines())
# print(fil2.readlines())
plagerism = check_plag(fil1,fil2)
print(plagerism)
fil1.close()
fil2.close()